version: "3.8"

services:
  frontend:
    container_name: pkmCardGameFront
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: pkmCardGameBack
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_ACCESS=mongodb+srv://brendanewen16:3BmFyuA4alqoB666@cluster0.3mfmcng.mongodb.net/?retryWrites=true&w=majority
      - SECRET_KEY=Zz47H.Aa5B
    networks:
      - pkmCardGameNet

  auth-microservice:
    container_name: pkmCardGameAuth
    build:
      context: ./backend/auth-microservice
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./backend/auth-microservice:/app
      - ./backend:/backend
    environment:
      - DATABASE_ACCESS=mongodb+srv://brendanewen16:3BmFyuA4alqoB666@cluster0.3mfmcng.mongodb.net/?retryWrites=true&w=majority
      - SECRET_KEY=Zz47H.Aa5B
    networks:
      - pkmCardGameNet

  user-microservice:
    container_name: pkmCardGameUser
    build:
      context: ./backend/user-microservice
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./backend/user-microservice:/app
      - ./backend:/backend
    environment:
      - DATABASE_ACCESS=mongodb+srv://brendanewen16:3BmFyuA4alqoB666@cluster0.3mfmcng.mongodb.net/?retryWrites=true&w=majority
      - SECRET_KEY=Zz47H.Aa5B
    networks:
      - pkmCardGameNet

networks:
  pkmCardGameNet:

#PC 
#C:\Users\brend\Documents\Websites\pkmCardGame\frontend
#C:\Users\brend\Documents\Websites\pkmCardGame\frontend:/frontend
#C:\Users\brend\Documents\Websites\pkmCardGame\backend
#C:\Users\brend\Documents\Websites\pkmCardGame\backend:/backend

#LAPTOP
#/home/brendan/Documents/Websites/pkmCardGame/frontend
#/home/brendan/Documents/Websites/pkmCardGame/frontend:/frontend
#/home/brendan/Documents/Websites/pkmCardGame/backend
#/home/brendan/Documents/Websites/pkmCardGame/backend:/backend