version: "4.0"

services:
  frontend:
    container_name: pkmCardGameFront
    build:
      context: C:\Users\brend\Documents\Websites\pkmCardGame\frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - C:\Users\brend\Documents\Websites\pkmCardGame\frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: pkmCardGameBack
    build:
      context: C:\Users\brend\Documents\Websites\pkmCardGame\backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - C:\Users\brend\Documents\Websites\pkmCardGame\backend:/backend
    environment:
      - CHOKIDAR_USEPOLLING=true

