POST http://localhost:5002/userprofile
Content-Type: application/json

{
  "username": "adminuser",
  "dob": "1990-01-01T00:00:00.000Z"
}


# POST http://localhost:5000/app/login
# Content-Type: application/json

# {
#   "username": "adminuser",
#   "password": "Zx56Tt407.9s"
# }

# POST http://localhost:5001/signup
# Content-Type: application/json

# {
#   "fullName": "John Doe",
#   "username": "johndoe",
#   "email": "johndoe@example.com",
#   "password": "mypassword",
#   "dob": "1990-01-01",
#   "announcements": true
# }