CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(50) NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    Password NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Announcements BIT NOT NULL,
    IsGlobalAdmin BIT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE()
);